# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  forge: 
    cmds:
      - git fetch
      - code ./.craft/forge.code-workspace
    silent: true
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
